/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-09-18 22:05:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class forum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>teste</title>\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/padrao.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"background\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"navtop\">\r\n");
      out.write("        <a href=\"index.html\">\r\n");
      out.write("            <img src=\"imagens/logo/coliseu2.png\" class=\"imgsite\">\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"icheckbox_line-blue\"><input id=\"week_morning\" name=\"week_morning\" value=\"week_morning\" style=\"position: absolute; opacity: 0;\" type=\"checkbox\">\r\n");
      out.write("            <div class=\"icheck_line-icon\"></div>ManhÃ£<ins class=\"iCheck-helper\" style=\"position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;\"></ins></div>\r\n");
      out.write("\r\n");
      out.write("        <p align=\"center\"><b>Dia de Semana</b></p>\r\n");
      out.write("        <hr style=\"margin-top:0; margin-bottom:0; height:3px; visibility:hidden;\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"icheckbox_line-blue\"><input id=\"week_afternoon\" name=\"week_afternoon\" value=\"week_afternoon\" style=\"position: absolute; opacity: 0;\" type=\"checkbox\">\r\n");
      out.write("            <div class=\"icheck_line-icon\"></div>Tarde<ins class=\"iCheck-helper\" style=\"position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;\"></ins></div>\r\n");
      out.write("\r\n");
      out.write("        <hr style=\"margin-top:0; margin-bottom:0; height:3px; visibility:hidden;\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"icheckbox_line-blue\"><input id=\"week_night\" name=\"week_night\" value=\"week_night\" style=\"position: absolute; opacity: 0;\" type=\"checkbox\">\r\n");
      out.write("            <div class=\"icheck_line-icon\"></div>Noite<ins class=\"iCheck-helper\" style=\"position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;\"></ins></div>\r\n");
      out.write("\r\n");
      out.write("        <hr style=\"margin-top:0; margin-bottom:0; height:3px; visibility:hidden;\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"icheckbox_line-blue\"><input id=\"week_dawn\" name=\"week_dawn\" value=\"week_dawn\" style=\"position: absolute; opacity: 0;\" type=\"checkbox\">\r\n");
      out.write("            <div class=\"icheck_line-icon\"></div>Madrugada<ins class=\"iCheck-helper\" style=\"position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;\"></ins></div>\r\n");
      out.write("\r\n");
      out.write("        <hr style=\"margin-top:0; margin-bottom:0; height:3px; visibility:hidden;\">\r\n");
      out.write("\r\n");
      out.write("        <p align=\"center\"><b>Final de Semana</b></p>\r\n");
      out.write("        <div class=\"icheckbox_line-green\"><input id=\"weekend_morning\" name=\"weekend_morning\" value=\"weekend_morning\" style=\"position: absolute; opacity: 0;\" type=\"checkbox\">\r\n");
      out.write("            <div class=\"icheck_line-icon\"></div>ManhÃ£<ins class=\"iCheck-helper\" style=\"position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;\"></ins></div>\r\n");
      out.write("\r\n");
      out.write("        <hr style=\"margin-top:0; margin-bottom:0; height:3px; visibility:hidden;\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"icheckbox_line-green\"><input id=\"weekend_afternoon\" name=\"weekend_afternoon\" value=\"weekend_afternoon\" style=\"position: absolute; opacity: 0;\" type=\"checkbox\">\r\n");
      out.write("            <div class=\"icheck_line-icon\"></div>Tarde<ins class=\"iCheck-helper\" style=\"position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;\"></ins></div>\r\n");
      out.write("\r\n");
      out.write("        <hr style=\"margin-top:0; margin-bottom:0; height:3px; visibility:hidden;\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"icheckbox_line-green\"><input id=\"weekend_night\" name=\"weekend_night\" value=\"weekend_night\" style=\"position: absolute; opacity: 0;\" type=\"checkbox\">\r\n");
      out.write("            <div class=\"icheck_line-icon\"></div>Noite<ins class=\"iCheck-helper\" style=\"position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;\"></ins></div>\r\n");
      out.write("\r\n");
      out.write("        <hr style=\"margin-top:0; margin-bottom:0; height:3px; visibility:hidden;\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"icheckbox_line-green\"><input id=\"weekend_dawn\" name=\"weekend_dawn\" value=\"weekend_dawn\" style=\"position: absolute; opacity: 0;\" type=\"checkbox\">\r\n");
      out.write("            <div class=\"icheck_line-icon\"></div>Madrugada<ins class=\"iCheck-helper\" style=\"position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;\"></ins></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <a href=\"javascript:\" id=\"return-to-top\"><i class=\"glyphicon glyphicon-chevron-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("        <!-- jQuery -->\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("        <!-- jQuery -->\r\n");
      out.write("        <script src=\"js/cadastro.js\"></script>\r\n");
      out.write("        <script src=\"js/padrao.js\"></script>\r\n");
      out.write("        <!-- Bootstrap JavaScript -->\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
