/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-09-20 00:10:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import br.com.arena21.dao.SalaDao;

public final class salas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("br.com.arena21.dao.SalaDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!Doctype html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"pt-br\" class=\"no-js\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("    <!-- CSS reset -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/padrao.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/pesquisa.css\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Resource style -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Modernizr -->\r\n");
      out.write("\r\n");
      out.write("    <title>Salas Jogos</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"background\"></div>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Topo -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <nav class=\"row navtop col-md-12\">\r\n");
      out.write("                    <a href=\"index.html\">\r\n");
      out.write("                        <img src=\"imagens/logo/coliseu2.png\" class=\"imgsite\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <main class=\"cd-main-content\">\r\n");
      out.write("            <div class=\"cd-tab-filter-wrapper\">\r\n");
      out.write("                <div class=\"cd-tab-filter\">\r\n");
      out.write("                    <ul class=\"cd-filters\">\r\n");
      out.write("                        <li class=\"placeholder\">\r\n");
      out.write("                            <a data-type=\"all\" href=\"#\">All</a>\r\n");
      out.write("                            <!-- selected option on mobile -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"filter\"><a class=\"selected\" href=\"#\" data-type=\"all\">Todas Salas</a></li>\r\n");
      out.write("                        <li class=\"filter\" data-filter=\".aberta\"><a href=\"#\" data-type=\"color-1\">Aberta</a></li>\r\n");
      out.write("                        <li class=\"filter\" data-filter=\".privada\"><a href=\"#\" data-type=\"color-2\">Privada</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- cd-filters -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- cd-tab-filter -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- cd-tab-filter-wrapper -->\r\n");
      out.write("\r\n");
      out.write("            <section class=\"cd-gallery\">                 \r\n");
      out.write("                    <div class=\"container \">\r\n");
      out.write("                            \r\n");
      out.write("                         \r\n");
      out.write("       \t\t\t\t\t\t\t ");

                            		out.print(new SalaDao().exibirSalas());
                            	
      out.write("                            \r\n");
      out.write("                                  <link async href=\"http://fonts.googleapis.com/css?family=Aladin\" data-generated=\"http://enjoycss.com\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("                        <link async href=\"http://fonts.googleapis.com/css?family=Open%20Sans\" data-generated=\"http://enjoycss.com\" rel=\"stylesheet\" type=\"text/css\" />      \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"cd-fail-message\">No results found</div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- cd-gallery -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cd-filter\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <div class=\"cd-filter-block\">\r\n");
      out.write("                        <h4>Procura</h4>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"cd-filter-content cd-filters\" >\r\n");
      out.write("                            <input type=\"text\" id=\"input\" value=\"\" placeholder=\"Nome Jogo\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- cd-filter-content -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- cd-filter-block -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"cd-filter-block\">\r\n");
      out.write("                        <h4>Encontre uma sala</h4>\r\n");
      out.write("                        <ul class=\"cd-filter-content cd-filters list\">\r\n");
      out.write("                          \r\n");
      out.write("                            <div class=\"cd-filter-content\">\r\n");
      out.write("                                <input type=\"search\" placeholder=\"Nome da Sala\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- cd-filter-content -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- cd-filter-block -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"cd-filter-block\">\r\n");
      out.write("                        <h4> Cidades </h4>\r\n");
      out.write("                        <div class=\"cd-filter-content\">\r\n");
      out.write("                            <div id=\"cidadeEstado\" class=\" cd-filters\">\r\n");
      out.write("                                        <select   id=\"estado1\" value=\"Selecione Estado\"></select>\r\n");
      out.write("                                        <select   id=\"cidade1\" value=\"Selecione Cidade\"></select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- cd-select -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- cd-filter-content -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- cd-filter-block --> \r\n");
      out.write("                </form>\r\n");
      out.write("                <a href=\"#0\" class=\"cd-close\">Close</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- cd-filter -->\r\n");
      out.write("            <a href=\"#0\" class=\"cd-filter-trigger\">Filtro</a>\r\n");
      out.write("        </main>\r\n");
      out.write("        <div>\r\n");
      out.write("                <footer>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-10\">\r\n");
      out.write("                                <small>Â© 2018 Copyright:</small>\r\n");
      out.write("                                <strong>Ademilson \r\n");
      out.write("                                        Adolfo\r\n");
      out.write("                                        Marcos\r\n");
      out.write("                                        Sergio\r\n");
      out.write("                                </strong>\r\n");
      out.write("                            </div>\r\n");
      out.write("        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </footer>\r\n");
      out.write("        </div>\r\n");
      out.write("                <a href=\"javascript:\" id=\"return-to-top\"><i class=\"glyphicon glyphicon-chevron-up\"></i></a>\r\n");
      out.write("        <!-- cd-main-content -->\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("        <script src=\"js/jquery.mixitup.min.js\"></script>\r\n");
      out.write("        <script src=\"js/main.js\"></script>\r\n");
      out.write("        <script src=\"js/padrao.js\"></script>\r\n");
      out.write("        <script src=\"js/modernizr.js\"></script>\r\n");
      out.write("        <script language=\"JavaScript\" type=\"text/javascript\" src=\"js/cidades-estados-utf8.js\"></script>\r\n");
      out.write("        <!-- Resource jQuery -->\r\n");
      out.write("        <script language=\"JavaScript\" type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("            new dgCidadesEstados({\r\n");
      out.write("              cidade: document.getElementById('cidade1'),\r\n");
      out.write("              estado: document.getElementById('estado1')\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
